<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-45K6V1V" ignored="0" name="Test" tests="7" failures="1" timestamp="2020-08-25T15:24:53 EDT" time="130.649" errors="0">
  <testcase name="validateDropdownCount" time="0.551" classname="UI.chefhero.validateHomepage"/>
  <testcase name="validateNavBarItems" time="0.826" classname="UI.chefhero.validateHomepage"/>
  <testcase name="validatelogin" time="18.398" classname="UI.chefhero.validateLoginPage"/>
  <testcase name="validatelogin" time="17.79" classname="UI.chefhero.validateLoginPage"/>
  <testcase name="validateAndroidReview" time="3.198" classname="UI.chefhero.validateUserReviews">
    <failure type="java.lang.AssertionError" message="expected [4] but found [4.7]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [4.7]
at UI.chefhero.validateUserReviews.validateAndroidReview(validateUserReviews.java:68)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validateAndroidReview -->
  <testcase name="validateIOSReview" time="4.379" classname="UI.chefhero.validateUserReviews"/>
  <testcase name="runScenario" time="16.676" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Test -->
