<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-45K6V1V" failures="1" tests="7" name="Test" time="131.821" errors="0" timestamp="2020-08-25T15:30:03 EDT">
  <testcase classname="UI.chefhero.validateHomepage" name="validateDropdownCount" time="0.643"/>
  <testcase classname="UI.chefhero.validateHomepage" name="validateNavBarItems" time="1.75"/>
  <testcase classname="UI.chefhero.validateLoginPage" name="validatelogin" time="19.454"/>
  <testcase classname="UI.chefhero.validateLoginPage" name="validatelogin" time="18.862"/>
  <testcase classname="UI.chefhero.validateUserReviews" name="validateAndroidReview" time="3.665">
    <failure type="java.lang.AssertionError" message="expected [4] but found [4.7]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [4.7]
at UI.chefhero.validateUserReviews.validateAndroidReview(validateUserReviews.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- validateAndroidReview -->
  <testcase classname="UI.chefhero.validateUserReviews" name="validateIOSReview" time="4.18"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.263"/>
</testsuite> <!-- Test -->
